# Generated by Django 5.1.6 on 2025-02-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('contact', models.CharField(default='Null', max_length=10)),
                ('Dob', models.DateField()),
                ('Password', models.CharField(max_length=15)),
                ('Cpassword', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
