# Generated by Django 5.1.6 on 2025-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='Cpassword',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='Dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='Username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
