# Generated by Django 5.1.6 on 2025-02-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_rename_cpassword_usermodel_cpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_superuser',
        ),
    ]
