# Generated by Django 5.1.6 on 2025-02-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_remove_usermodel_is_active_remove_usermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
    ]
