# Generated by Django 5.1.6 on 2025-02-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingridients',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
