# Generated by Django 5.1.6 on 2025-02-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_product_ingridients_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingridients',
            new_name='ingredients',
        ),
    ]
