# Generated by Django 5.1.6 on 2025-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='flavor',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='shape',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
