# Generated by Django 5.1.6 on 2025-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_cart_flavor_cart_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='weight',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
