# Generated by Django 5.1.6 on 2025-02-25 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0012_review'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='cart',
    #         name='flavor',
    #         field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='cake.flavor'),
    #     ),
    #     migrations.AlterField(
    #         model_name='cart',
    #         name='shape',
    #         field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='cake.shape'),
    #     ),
    # ]
