# Generated by Django 5.1.6 on 2025-02-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0013_alter_cart_flavor_alter_cart_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='flavor',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shape',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
