# Generated by Django 5.1.6 on 2025-02-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0014_alter_cart_flavor_alter_cart_shape'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='cart',
        #     name='flavor',
        # ),
        migrations.RemoveField(
            model_name='cart',
            name='shape',
        ),
    ]
