# Generated by Django 5.1.6 on 2025-03-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0016_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
