# Generated by Django 5.1.6 on 2025-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0017_remove_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='flavor',
            field=models.CharField(default='vanila', max_length=50),
        ),
    ]
