# Generated by Django 5.1.6 on 2025-03-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0018_cart_flavor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='flavor',
        ),
    ]
