# Generated by Django 5.1.6 on 2025-03-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0021_remove_cart_shape'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='cart',
    #         name='shape',
    #     ),
    # ]
