# Generated by Django 5.1.6 on 2025-03-16 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0024_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
