# Generated by Django 5.1.6 on 2025-03-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0025_usermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='flavor',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='shape',
            field=models.CharField(default='round', max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='weight',
            field=models.CharField(default='300g', max_length=10),
        ),
    ]
