# Generated by Django 5.1.6 on 2025-03-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0026_cart_flavor_cart_shape_alter_cart_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='flavor',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
