# Generated by Django 5.1.6 on 2025-03-17 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0028_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('delivery_name', models.CharField(max_length=50)),
                ('contact', models.CharField(default='Null', max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('weight', models.CharField(default='300g', max_length=10)),
                ('shape', models.CharField(default='round', max_length=20)),
                ('flavor', models.CharField(default=None, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
            ],
        ),
    ]
