# Generated by Django 5.1.6 on 2025-03-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0029_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
