# Generated by Django 5.1.6 on 2025-03-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0031_blog_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('issue', models.TextField(max_length=500)),
                ('ans', models.TextField(max_length=500)),
            ],
        ),
    ]
