# Generated by Django 5.1.6 on 2025-03-24 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0032_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
