# Generated by Django 5.1.6 on 2025-03-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0033_blog_date_inquiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.CharField(max_length=20)),
                ('weekly_order', models.IntegerField(default=0)),
                ('weekly_income', models.IntegerField(default=0)),
                ('month_start', models.CharField(max_length=20)),
                ('monthly_order', models.IntegerField(default=0)),
                ('monthly_income', models.IntegerField(default=0)),
            ],
        ),
    ]
