# Generated by Django 5.1.6 on 2025-03-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0034_reports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reports',
            new_name='report',
        ),
    ]
