# Generated by Django 5.1.6 on 2025-03-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0035_rename_reports_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report',
        ),
    ]
