# Generated by Django 5.1.6 on 2025-03-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0036_delete_report'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='order',
    #         name='order_id',
    #         field=models.CharField(default='Null', max_length=10, unique=True),
    #     ),
    # ]
