# Generated by Django 5.1.6 on 2025-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0037_order_order_id'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='order',
    #         name='order_id',
    #         field=models.CharField(default='1', max_length=10, unique=True),
    #     ),
    # ]
