# Generated by Django 5.1.6 on 2025-03-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0038_alter_order_order_id'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='order',
    #         name='order_id',
    #     ),
    # ]
